### ISSUE TITLE
Formatter 사용 권장

### ISSUE THREAD

**Issue by freesens** [jonghyeShin/study#1]
Eclipse를 사용중이라면 Ctrl + Shift + F로 코드 포맷팅이 가능한데, 읽기 쉬운 코드 작성을 위해 포매터 사용을 권장함.
(intelliJ라면 Ctrl + Alt + L)
다만, html파일에서 사용시 html코드까지 정의된 규칙대로 맞춰질 수 있으니, js 코드 부분만 블럭 설정 후 포매터 실행 권장.

큰 차이는 없으나, 띄어쓰기나 엔터, 괄호위치 등을 항상 일정한 규칙으로 맞춰줌.

https://github.com/jonghyeShin/study/blob/8e94ba7f00df6d62af9308b4fbb21e07d5ff7aec/study/WebContent/chapter3/example.jsp#L11

**Comment by jonghyeShin** [comment]
넵!!!
